/*
Copyright (C) 2025 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/

export const MOCK_VENDORS = [
  { id: 'openai', name: 'OpenAI', icon: 'OpenAI.Color', description: 'OpenAI 是全球领先的人工智能研究公司，提供 GPT 系列大语言模型。' },
  { id: 'anthropic', name: 'Anthropic', icon: 'Claude.Color', description: 'Anthropic 专注于 AI 安全研究，提供 Claude 系列对话模型。' },
  { id: 'google', name: 'Google', icon: 'Gemini.Color', description: 'Google DeepMind 推出的 Gemini 系列多模态大模型。' },
  { id: 'moonshot', name: 'Moonshot', icon: 'Moonshot.Color', description: '月之暗面科技，提供 Kimi 长文本对话模型。' },
  { id: 'deepseek', name: 'DeepSeek', icon: 'DeepSeek.Color', description: '深度求索，提供高性价比的 DeepSeek 系列大语言模型。' },
  { id: 'zhipu', name: '智谱 AI', icon: 'Zhipu.Color', description: '智谱 AI，提供 ChatGLM / GLM 系列中文大语言模型。' },
  { id: 'baidu', name: '百度', icon: 'Wenxin.Color', description: '百度文心一言，提供文心系列中文大语言模型。' },
  { id: 'alibaba', name: '阿里云', icon: 'Tongyi.Color', description: '阿里云通义千问，提供 Qwen 系列大语言模型。' },
  { id: 'xai', name: 'xAI', icon: 'Grok.Color', description: 'xAI 由 Elon Musk 创立，提供 Grok 系列大语言模型。' },
  { id: 'meta', name: 'Meta', icon: 'Meta.Color', description: 'Meta AI 推出的 Llama 系列开源大语言模型。' },
];

export const MOCK_GROUP_RATIO = {
  default: 1,
  vip: 0.8,
  svip: 0.6,
  enterprise: 0.5,
  trial: 1.5,
};

export const MOCK_USABLE_GROUP = {
  default: true,
  vip: true,
  svip: true,
  enterprise: true,
  trial: true,
};

export const MOCK_SUPPORTED_ENDPOINT = {
  chat_completions: 'Chat Completions',
  embeddings: 'Embeddings',
  images: 'Images',
  audio: 'Audio',
};

export const MOCK_AUTO_GROUPS = ['default', 'vip', 'svip'];

export const MOCK_MODELS = [
  {
    model_name: 'gpt-4o',
    description: 'OpenAI 旗舰多模态模型，支持文本、图像、音频输入，具备强大的推理和创作能力。',
    tags: '多模态,推理,创作',
    quota_type: 0,
    model_ratio: 2.5,
    completion_ratio: 1.0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'openai',
    icon: 'OpenAI.Color',
  },
  {
    model_name: 'gpt-4o-mini',
    description: 'OpenAI 轻量级多模态模型，速度快、成本低，适合日常对话和简单任务。',
    tags: '多模态,轻量,快速',
    quota_type: 0,
    model_ratio: 0.15,
    completion_ratio: 1.0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise', 'trial'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'openai',
    icon: 'OpenAI.Color',
  },
  {
    model_name: 'gpt-4-turbo',
    description: 'OpenAI 高性能模型，具备 128K 上下文窗口，适合长文档分析和复杂推理。',
    tags: '长文本,推理,分析',
    quota_type: 0,
    model_ratio: 10,
    completion_ratio: 1.0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'openai',
    icon: 'OpenAI.Color',
  },
  {
    model_name: 'o1-preview',
    description: 'OpenAI 推理模型，在科学、数学和编程等复杂任务上表现优异。',
    tags: '推理,科学,编程',
    quota_type: 0,
    model_ratio: 15,
    completion_ratio: 1.0,
    enable_groups: ['vip', 'svip', 'enterprise'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'openai',
    icon: 'OpenAI.Color',
  },
  {
    model_name: 'o1-mini',
    description: 'OpenAI 轻量推理模型，在代码和数学任务上有出色表现，成本更低。',
    tags: '推理,编程,数学',
    quota_type: 0,
    model_ratio: 3,
    completion_ratio: 1.0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise', 'trial'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'openai',
    icon: 'OpenAI.Color',
  },
  {
    model_name: 'text-embedding-3-large',
    description: 'OpenAI 高性能文本嵌入模型，适用于语义搜索和相似度计算。',
    tags: '嵌入,搜索,相似度',
    quota_type: 0,
    model_ratio: 0.13,
    completion_ratio: 0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise'],
    supported_endpoint_types: ['embeddings'],
    vendor_id: 'openai',
    icon: 'OpenAI.Color',
  },
  {
    model_name: 'claude-3-5-sonnet-20241022',
    description: 'Anthropic Claude 3.5 Sonnet，在推理、代码和创意写作方面表现卓越。',
    tags: '推理,代码,创意',
    quota_type: 0,
    model_ratio: 3,
    completion_ratio: 1.0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'anthropic',
    icon: 'Claude.Color',
  },
  {
    model_name: 'claude-3-opus-20240229',
    description: 'Anthropic 最强模型，在处理复杂任务、长文档和深度分析方面领先。',
    tags: '顶级,长文本,分析',
    quota_type: 0,
    model_ratio: 15,
    completion_ratio: 1.0,
    enable_groups: ['vip', 'svip', 'enterprise'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'anthropic',
    icon: 'Claude.Color',
  },
  {
    model_name: 'claude-3-haiku-20240307',
    description: 'Anthropic 轻量快速模型，适合日常对话和简单问答。',
    tags: '轻量,快速,日常',
    quota_type: 0,
    model_ratio: 0.25,
    completion_ratio: 1.0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise', 'trial'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'anthropic',
    icon: 'Claude.Color',
  },
  {
    model_name: 'gemini-1.5-pro',
    description: 'Google Gemini 1.5 Pro，支持 100万+ 上下文，多模态理解和推理能力强大。',
    tags: '多模态,长文本,推理',
    quota_type: 0,
    model_ratio: 1.25,
    completion_ratio: 1.0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'google',
    icon: 'Gemini.Color',
  },
  {
    model_name: 'gemini-1.5-flash',
    description: 'Google Gemini 1.5 Flash，速度快、成本低，适合高并发场景。',
    tags: '快速,轻量,高并发',
    quota_type: 0,
    model_ratio: 0.075,
    completion_ratio: 1.0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise', 'trial'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'google',
    icon: 'Gemini.Color',
  },
  {
    model_name: 'kimi-k1.5',
    description: 'Moonshot Kimi k1.5，支持超长上下文，在中文理解和长文档处理上表现优异。',
    tags: '长文本,中文,文档',
    quota_type: 0,
    model_ratio: 1,
    completion_ratio: 1.0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'moonshot',
    icon: 'Moonshot.Color',
  },
  {
    model_name: 'deepseek-chat',
    description: 'DeepSeek V3，具备强大的代码能力和数学推理，性价比极高。',
    tags: '代码,数学,性价比',
    quota_type: 0,
    model_ratio: 0.07,
    completion_ratio: 1.0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise', 'trial'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'deepseek',
    icon: 'DeepSeek.Color',
  },
  {
    model_name: 'deepseek-reasoner',
    description: 'DeepSeek R1，推理模型，在复杂推理和数学证明任务上表现突出。',
    tags: '推理,数学,证明',
    quota_type: 0,
    model_ratio: 0.14,
    completion_ratio: 1.0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'deepseek',
    icon: 'DeepSeek.Color',
  },
  {
    model_name: 'glm-4-plus',
    description: '智谱 GLM-4 Plus，中文理解能力领先，支持多轮对话和复杂指令。',
    tags: '中文,对话,指令',
    quota_type: 0,
    model_ratio: 0.5,
    completion_ratio: 1.0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'zhipu',
    icon: 'Zhipu.Color',
  },
  {
    model_name: 'glm-4-flash',
    description: '智谱 GLM-4 Flash，轻量快速，适合日常对话和简单任务。',
    tags: '轻量,快速,中文',
    quota_type: 0,
    model_ratio: 0.05,
    completion_ratio: 1.0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise', 'trial'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'zhipu',
    icon: 'Zhipu.Color',
  },
  {
    model_name: 'ernie-4.0-turbo-8k',
    description: '百度文心 4.0 Turbo，中文知识增强，在中文场景下表现优异。',
    tags: '中文,知识,增强',
    quota_type: 0,
    model_ratio: 0.6,
    completion_ratio: 1.0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'baidu',
    icon: 'Wenxin.Color',
  },
  {
    model_name: 'qwen-max',
    description: '阿里云通义千问 Max，在中文理解、代码和数学推理上表现优秀。',
    tags: '中文,代码,数学',
    quota_type: 0,
    model_ratio: 0.5,
    completion_ratio: 1.0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'alibaba',
    icon: 'Tongyi.Color',
  },
  {
    model_name: 'qwen-plus',
    description: '阿里云通义千问 Plus，平衡性能和成本，适合大多数应用场景。',
    tags: '平衡,通用,中文',
    quota_type: 0,
    model_ratio: 0.1,
    completion_ratio: 1.0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise', 'trial'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'alibaba',
    icon: 'Tongyi.Color',
  },
  {
    model_name: 'grok-2',
    description: 'xAI Grok 2，具备实时信息获取能力和独特的幽默风格。',
    tags: '实时,幽默,创新',
    quota_type: 0,
    model_ratio: 5,
    completion_ratio: 1.0,
    enable_groups: ['vip', 'svip', 'enterprise'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'xai',
    icon: 'Grok.Color',
  },
  {
    model_name: 'llama-3.3-70b',
    description: 'Meta Llama 3.3 70B，开源大模型中的佼佼者，推理能力强劲。',
    tags: '开源,推理,通用',
    quota_type: 0,
    model_ratio: 0.2,
    completion_ratio: 1.0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise', 'trial'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'meta',
    icon: 'Meta.Color',
  },
  {
    model_name: 'dall-e-3',
    description: 'OpenAI DALL-E 3，根据文本描述生成高质量图像。',
    tags: '图像生成,创意,设计',
    quota_type: 1,
    model_ratio: 0,
    completion_ratio: 0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise'],
    supported_endpoint_types: ['images'],
    vendor_id: 'openai',
    icon: 'OpenAI.Color',
  },
  {
    model_name: 'whisper-1',
    description: 'OpenAI Whisper，语音识别模型，支持多语言语音转文字。',
    tags: '语音,识别,多语言',
    quota_type: 1,
    model_ratio: 0,
    completion_ratio: 0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise'],
    supported_endpoint_types: ['audio'],
    vendor_id: 'openai',
    icon: 'OpenAI.Color',
  },
  {
    model_name: 'gpt-4o-realtime-preview',
    description: 'OpenAI 实时语音对话模型，支持低延迟语音交互。',
    tags: '实时,语音,对话',
    quota_type: 0,
    model_ratio: 5,
    completion_ratio: 1.0,
    enable_groups: ['vip', 'svip', 'enterprise'],
    supported_endpoint_types: ['chat_completions', 'audio'],
    vendor_id: 'openai',
    icon: 'OpenAI.Color',
  },
  {
    model_name: 'deepseek-coder',
    description: 'DeepSeek Coder，专为代码生成和补全优化的模型。',
    tags: '代码,编程,补全',
    quota_type: 0,
    model_ratio: 0.07,
    completion_ratio: 1.0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise', 'trial'],
    supported_endpoint_types: ['chat_completions'],
    vendor_id: 'deepseek',
    icon: 'DeepSeek.Color',
  },
  {
    model_name: 'gemini-embedding-exp',
    description: 'Google Gemini 嵌入模型，多语言文本嵌入，适用于语义搜索。',
    tags: '嵌入,搜索,多语言',
    quota_type: 0,
    model_ratio: 0.05,
    completion_ratio: 0,
    enable_groups: ['default', 'vip', 'svip', 'enterprise'],
    supported_endpoint_types: ['embeddings'],
    vendor_id: 'google',
    icon: 'Gemini.Color',
  },
];

export const getMockPricingData = () => ({
  success: true,
  data: MOCK_MODELS,
  vendors: MOCK_VENDORS,
  group_ratio: MOCK_GROUP_RATIO,
  usable_group: MOCK_USABLE_GROUP,
  supported_endpoint: MOCK_SUPPORTED_ENDPOINT,
  auto_groups: MOCK_AUTO_GROUPS,
});
